apiVersion: v1
kind: Pod
metadata:
  name: aws-test
  namespace: default
spec:
  serviceAccountName: example-sa
  containers:
  - name: aws-test
    image: amazon/aws-cli
    command: ["aws"]
    args: ["sts", "get-caller-identity"]
